console.log("Pirate")

import fs from 'fs'

function readFile () {
    console.log("Started Reading File:")
    const response = fs.readFile("./data", "utf-8", (err, data) => {
        if(err) return err
        console.log(data)
    })
    console.log("Ended Reading File")
}

readFile()
console.log("King")

const value = "eyJzX3JlbW90ZV9pZCI6bnVsbCwidmlzaXRvcl9pZCI6IjkzNDFkNGE3LWYxMDMtNGVhYy1iYWE0LTMxNDNlYTc4MTFiNiIsImVjb21fc2Vzc2lvbl9pZCI6IjJmYWRlNTZjLTY4MjctNGU4OS05NDhjLWI0ZTM3MzFiMWE4MyIsInRlbmFudF9pZCI6IlVTQSIsImNsaWVudF9pZGVudGl0eSI6eyJpc1lhQnJvd3NlciI6ZmFsc2UsImlzQXV0aG9yaXRhdGl2ZSI6ZmFsc2UsImlzTW9iaWxlIjp0cnVlLCJpc01vYmlsZU5hdGl2ZSI6ZmFsc2UsImlzVGFibGV0Ijp0cnVlLCJpc2lQYWQiOmZhbHNlLCJpc2lQb2QiOmZhbHNlLCJpc2lQaG9uZSI6ZmFsc2UsImlzaVBob25lTmF0aXZlIjpmYWxzZSwiaXNBbmRyb2lkIjp0cnVlLCJpc0FuZHJvaWROYXRpdmUiOmZhbHNlLCJpc0JsYWNrYmVycnkiOmZhbHNlLCJpc09wZXJhIjpmYWxzZSwiaXNJRSI6ZmFsc2UsImlzRWRnZSI6ZmFsc2UsImlzSUVDb21wYXRpYmlsaXR5TW9kZSI6ZmFsc2UsImlzU2FmYXJpIjpmYWxzZSwiaXNGaXJlZm94IjpmYWxzZSwiaXNXZWJraXQiOmZhbHNlLCJpc0Nocm9tZSI6ZmFsc2UsImlzS29ucXVlcm9yIjpmYWxzZSwiaXNPbW5pV2ViIjpmYWxzZSwiaXNTZWFNb25rZXkiOmZhbHNlLCJpc0Zsb2NrIjpmYWxzZSwiaXNBbWF5YSI6ZmFsc2UsImlzUGhhbnRvbUpTIjpmYWxzZSwiaXNFcGlwaGFueSI6ZmFsc2UsImlzRGVza3RvcCI6ZmFsc2UsImlzV2luZG93cyI6ZmFsc2UsImlzTGludXgiOmZhbHNlLCJpc0xpbnV4NjQiOmZhbHNlLCJpc01hYyI6ZmFsc2UsImlzQ2hyb21lT1MiOmZhbHNlLCJpc0JhZGEiOmZhbHNlLCJpc1NhbXN1bmciOmZhbHNlLCJpc1Jhc3BiZXJyeSI6ZmFsc2UsImlzQm90IjpmYWxzZSwiaXNDdXJsIjpmYWxzZSwiaXNBbmRyb2lkVGFibGV0Ijp0cnVlLCJpc1dpbkpzIjpmYWxzZSwiaXNLaW5kbGVGaXJlIjpmYWxzZSwiaXNTaWxrIjpmYWxzZSwiaXNDYXB0aXZlIjpmYWxzZSwiaXNTbWFydFRWIjpmYWxzZSwiaXNVQyI6ZmFsc2UsImlzRmFjZWJvb2siOmZhbHNlLCJpc0FsYW1vRmlyZSI6ZmFsc2UsImlzRWxlY3Ryb24iOmZhbHNlLCJzaWxrQWNjZWxlcmF0ZWQiOmZhbHNlLCJicm93c2VyIjoiU2hvcFNhbXN1bmctQW5kcm9pZCIsInZlcnNpb24iOiIyLjAuMzU0MDEiLCJvcyI6InVua25vd24iLCJwbGF0Zm9ybSI6IkFuZHJvaWQiLCJnZW9JcCI6e30sInNvdXJjZSI6IlNob3BTYW1zdW5nLUFuZHJvaWQvMi4wLjM1NDAxL1NNLVM5MjhVMSAoY29tLnNhbXN1bmcuZWNvbW06MzYpIiwiaXNXZWNoYXQiOmZhbHNlLCJlbGVjdHJvblZlcnNpb24iOiIiLCJpcEFkZHJlc3MiOiI3My4zNi4xNTIuNDEiLCJwb3J0Ijo1Nzk3NiwidWEiOiJTaG9wU2Ftc3VuZy1BbmRyb2lkLzIuMC4zNTQwMS9TTS1TOTI4VTEgKGNvbS5zYW1zdW5nLmVjb21tOjM2KSIsImRldGVjdGVkVUEiOiJTaG9wU2Ftc3VuZy1BbmRyb2lkIiwiZGV2aWNlVHlwZSI6IlRhYmxldCIsImNsaWVudFR5cGUiOiJNb2JpbGVBcHAiLCJjbGllbnRTb3VyY2UiOiJTaG9wQXBwIn0sInNvdXJjZV9hcHBfaWQiOiJzYW1zdW5nLW1vYmlsZS1hcHAiLCJrZXlfaWQiOiJzYW1zdW5nLW1vYmlsZS1hcHAvcHVibGljX2tleS92MSJ9"
const v = Buffer.from(value, 'base64');
console.log(JSON.parse(v), "FDS")
fs.writeFileSync("./fsdfds", JSON.stringify(JSON.parse(v), null, 2))
